version: '3'
services:
  api:
    build: ./api
    volumes: 
      - ./api:/app
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  nginx:
    image: nginx:1.25.5
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80